name: Upload ETL Code

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy ETL to S3 bucket
      run: aws s3 sync ./public/ s3://sparkify-etl-code-df --delete
